const plants = [
  { id: "BLM", name: "Bloomfield", state: "CT", timezone: "America/New_York" },
  { id: "JAX", name: "Jacksonville", state: "FL", timezone: "America/New_York" },
  { id: "LAN", name: "Lancaster", state: "TX", timezone: "America/Chicago" },
  { id: "ONT", name: "Ontario", state: "CA", timezone: "America/Los_Angeles" },
];

const inspection = (id, name, type, result, possibleCauses = [], recommendations = [], reading = null) => ({
  id,
  name,
  type,
  result,
  possibleCauses,
  recommendations,
  reading,
});

const attachment = (id, name, kind, inspectionPoint = null, size = "1.2 MB") => ({
  id,
  name,
  kind,
  inspectionPoint,
  size,
});

const mission = ({ id, robotId, plantId, startTime, endTime, status, inspections, attachments = [], route }) => ({
  id,
  eventId: `evt-${id.toLowerCase()}`,
  runId: `run-${id.slice(-4).toLowerCase()}`,
  actionId: `action-${id.slice(-4).toLowerCase()}`,
  robotId,
  plantId,
  startTime,
  endTime,
  status,
  route,
  inspections,
  attachments,
  source: "Orbit via Litmus",
  correlationId: `corr-${id.slice(-4).toLowerCase()}-arch`,
});

const missions = [
  mission({
    id: "SPOT-BLM-0910-042",
    robotId: "SPOT-BD-52240",
    plantId: "BLM",
    startTime: "2026-09-10T18:32:00Z",
    endTime: "2026-09-10T18:48:22Z",
    status: "Complete",
    route: "Blow Molder Line 4",
    inspections: [
      inspection("IP-401", "Main drive motor", "Thermal", "Pass", [], ["Continue standard monitoring"], "71.4 °C"),
      inspection("IP-402", "Compressor manifold", "Acoustic", "Fail", ["Bearing wear", "Loose mounting hardware"], ["Inspect coupling and bearing within 24 hours", "Verify mounting torque"], "84.2 dB"),
      inspection("IP-403", "Air header coupling", "Leak detection", "Fail", ["Seal degradation", "Loose fitting"], ["Isolate line and inspect seal", "Re-torque fitting to specification"], "Ultrasonic leak"),
      inspection("IP-404", "Electrical cabinet A", "Visual", "Pass", [], ["No action required"], "Clear"),
      inspection("IP-405", "Hydraulic power unit", "Thermal", "Pass", [], ["Continue standard monitoring"], "62.7 °C"),
    ],
    attachments: [
      attachment("ATT-042-A", "compressor-thermal-capture.svg", "Thermal image", "Compressor manifold", "780 KB"),
      attachment("ATT-042-B", "air-header-inspection.svg", "Inspection image", "Air header coupling", "1.4 MB"),
      attachment("ATT-042-C", "mission-042-report.txt", "Mission report", null, "18 KB"),
    ],
  }),
  mission({
    id: "SPOT-BLM-0910-041",
    robotId: "SPOT-BD-52240",
    plantId: "BLM",
    startTime: "2026-09-10T15:04:00Z",
    endTime: "2026-09-10T15:18:09Z",
    status: "Complete",
    route: "Utilities North Loop",
    inspections: [
      inspection("IP-311", "Chiller pump 1", "Thermal", "Pass", [], ["Continue standard monitoring"], "58.2 °C"),
      inspection("IP-312", "Chiller pump 2", "Acoustic", "Pass", [], ["Continue standard monitoring"], "66.1 dB"),
      inspection("IP-313", "Steam trap 12", "Leak detection", "Pass", [], ["No action required"], "Normal"),
      inspection("IP-314", "Utility corridor", "Visual", "Pass", [], ["No action required"], "Clear"),
    ],
    attachments: [attachment("ATT-041-A", "utilities-north-overview.svg", "Inspection image", "Utility corridor", "940 KB")],
  }),
  mission({
    id: "SPOT-JAX-0910-018",
    robotId: "SPOT-BD-48117",
    plantId: "JAX",
    startTime: "2026-09-10T13:10:00Z",
    endTime: null,
    status: "In Progress",
    route: "Filler Hall A",
    inspections: [
      inspection("IP-210", "Filler 1 gearcase", "Thermal", "Pass", [], ["Continue standard monitoring"], "64.8 °C"),
      inspection("IP-211", "Capper drive", "Acoustic", null, [], [], null),
      inspection("IP-212", "Conveyor transfer", "Visual", null, [], [], null),
    ],
  }),
  mission({
    id: "SPOT-LAN-0910-007",
    robotId: "SPOT-BD-61703",
    plantId: "LAN",
    startTime: "2026-09-10T12:40:00Z",
    endTime: null,
    status: "Not Started",
    route: "Warehouse South",
    inspections: [
      inspection("IP-701", "Dock door 6", "Visual", null),
      inspection("IP-702", "Fire pump room", "Thermal", null),
      inspection("IP-703", "Battery charging area", "Visual", null),
    ],
  }),
  mission({
    id: "SPOT-ONT-0909-063",
    robotId: "SPOT-BD-55281",
    plantId: "ONT",
    startTime: "2026-09-09T22:18:00Z",
    endTime: "2026-09-09T22:37:45Z",
    status: "Complete",
    route: "Compressor Room",
    inspections: [
      inspection("IP-601", "Compressor 3 motor", "Thermal", "Pass", [], ["Continue standard monitoring"], "73.8 °C"),
      inspection("IP-602", "Compressor 3 bearing", "Acoustic", "Fail", ["Early bearing defect", "Insufficient lubrication"], ["Collect vibration reading", "Review lubrication schedule"], "89.7 dB"),
      inspection("IP-603", "Receiver tank", "Visual", "Pass", [], ["No action required"], "Clear"),
      inspection("IP-604", "Condensate drain", "Leak detection", "Pass", [], ["No action required"], "Normal"),
    ],
    attachments: [
      attachment("ATT-063-A", "bearing-acoustic-spectrum.svg", "Acoustic capture", "Compressor 3 bearing", "630 KB"),
      attachment("ATT-063-B", "mission-063-report.txt", "Mission report", null, "16 KB"),
    ],
  }),
  mission({
    id: "SPOT-BLM-0909-040",
    robotId: "SPOT-BD-52240",
    plantId: "BLM",
    startTime: "2026-09-09T16:30:00Z",
    endTime: "2026-09-09T16:44:13Z",
    status: "Complete",
    route: "Resin Handling",
    inspections: [
      inspection("IP-391", "Silo blower 1", "Acoustic", "Pass", [], ["Continue standard monitoring"], "71.0 dB"),
      inspection("IP-392", "Silo blower 2", "Acoustic", "Pass", [], ["Continue standard monitoring"], "70.7 dB"),
      inspection("IP-393", "Dust collector", "Thermal", "Pass", [], ["No action required"], "51.3 °C"),
    ],
  }),
  mission({
    id: "SPOT-JAX-0908-017",
    robotId: "SPOT-BD-48117",
    plantId: "JAX",
    startTime: "2026-09-08T14:10:00Z",
    endTime: "2026-09-08T14:30:51Z",
    status: "Complete",
    route: "Boiler & Steam Loop",
    inspections: [
      inspection("IP-180", "Boiler feed pump", "Thermal", "Pass", [], ["Continue standard monitoring"], "69.1 °C"),
      inspection("IP-181", "Steam trap 4", "Leak detection", "Fail", ["Failed-open steam trap"], ["Schedule steam trap replacement"], "Continuous flow"),
      inspection("IP-182", "Steam trap 5", "Leak detection", "Pass", [], ["No action required"], "Normal"),
      inspection("IP-183", "Boiler sight glass", "Visual", "Pass", [], ["No action required"], "Clear"),
    ],
    attachments: [attachment("ATT-017-A", "steam-trap-4.svg", "Thermal image", "Steam trap 4", "810 KB")],
  }),
  mission({
    id: "SPOT-LAN-0908-006",
    robotId: "SPOT-BD-61703",
    plantId: "LAN",
    startTime: "2026-09-08T12:05:00Z",
    endTime: "2026-09-08T12:16:32Z",
    status: "Complete",
    route: "Warehouse North",
    inspections: [
      inspection("IP-681", "Dock door 1", "Visual", "Pass", [], ["No action required"], "Clear"),
      inspection("IP-682", "Dock door 2", "Visual", "Pass", [], ["No action required"], "Clear"),
      inspection("IP-683", "Sprinkler riser", "Thermal", "Pass", [], ["Continue standard monitoring"], "29.8 °C"),
    ],
  }),
  mission({
    id: "SPOT-ONT-0907-062",
    robotId: "SPOT-BD-55281",
    plantId: "ONT",
    startTime: "2026-09-07T21:02:00Z",
    endTime: "2026-09-07T21:21:10Z",
    status: "Complete",
    route: "Packaging Lines 5–6",
    inspections: [
      inspection("IP-621", "Labeler 5 drive", "Acoustic", "Pass", [], ["Continue standard monitoring"], "67.4 dB"),
      inspection("IP-622", "Packer 5 cabinet", "Thermal", "Pass", [], ["No action required"], "48.2 °C"),
      inspection("IP-623", "Conveyor 6 transfer", "Visual", "Pass", [], ["No action required"], "Clear"),
      inspection("IP-624", "Palletizer 6 motor", "Thermal", "Pass", [], ["Continue standard monitoring"], "61.5 °C"),
    ],
  }),
  mission({
    id: "SPOT-BLM-0906-039",
    robotId: "SPOT-BD-52240",
    plantId: "BLM",
    startTime: "2026-09-06T17:42:00Z",
    endTime: "2026-09-06T18:02:08Z",
    status: "Complete",
    route: "Blow Molder Line 3",
    inspections: [
      inspection("IP-351", "Oven chain drive", "Thermal", "Fail", ["High friction", "Lubrication issue"], ["Inspect and lubricate chain drive"], "92.4 °C"),
      inspection("IP-352", "Main air valve", "Leak detection", "Pass", [], ["No action required"], "Normal"),
      inspection("IP-353", "Transfer wheel", "Visual", "Pass", [], ["No action required"], "Clear"),
      inspection("IP-354", "Preform hopper", "Visual", "Pass", [], ["No action required"], "Clear"),
      inspection("IP-355", "Cooling fan bank", "Acoustic", "Pass", [], ["Continue standard monitoring"], "73.1 dB"),
    ],
    attachments: [attachment("ATT-039-A", "oven-chain-thermal.svg", "Thermal image", "Oven chain drive", "720 KB")],
  }),
  mission({
    id: "SPOT-JAX-0905-016",
    robotId: "SPOT-BD-48117",
    plantId: "JAX",
    startTime: "2026-09-05T13:00:00Z",
    endTime: "2026-09-05T13:13:19Z",
    status: "Complete",
    route: "Utilities South Loop",
    inspections: [
      inspection("IP-151", "Cooling tower pump", "Thermal", "Pass", [], ["Continue standard monitoring"], "59.7 °C"),
      inspection("IP-152", "Water treatment skid", "Visual", "Pass", [], ["No action required"], "Clear"),
      inspection("IP-153", "Air dryer 2", "Acoustic", "Pass", [], ["Continue standard monitoring"], "68.2 dB"),
    ],
  }),
  mission({
    id: "SPOT-ONT-0904-061",
    robotId: "SPOT-BD-55281",
    plantId: "ONT",
    startTime: "2026-09-04T20:33:00Z",
    endTime: "2026-09-04T20:48:44Z",
    status: "Complete",
    route: "Filler Line 2",
    inspections: [
      inspection("IP-611", "Filler bowl drive", "Thermal", "Pass", [], ["Continue standard monitoring"], "60.5 °C"),
      inspection("IP-612", "Capper spindle", "Acoustic", "Pass", [], ["Continue standard monitoring"], "65.0 dB"),
      inspection("IP-613", "Rinser enclosure", "Visual", "Pass", [], ["No action required"], "Clear"),
      inspection("IP-614", "Product manifold", "Leak detection", "Pass", [], ["No action required"], "Normal"),
    ],
  }),
];

const alerts = [
  {
    id: "ALT-2048",
    ticketKey: "SPOT-BLM-0910-042:IP-402:acoustic",
    missionId: "SPOT-BLM-0910-042",
    inspectionId: "IP-402",
    title: "Elevated acoustic signature",
    description: "Compressor manifold reading exceeded the approved acoustic threshold.",
    severity: "High",
    status: "Open",
    owner: "Reliability – BLM",
    createdAt: "2026-09-10T18:40:16Z",
    updatedAt: "2026-09-10T18:48:25Z",
  },
  {
    id: "ALT-2047",
    ticketKey: "SPOT-BLM-0910-042:IP-403:leak",
    missionId: "SPOT-BLM-0910-042",
    inspectionId: "IP-403",
    title: "Compressed air leak detected",
    description: "Ultrasonic inspection identified a probable leak at the air header coupling.",
    severity: "Medium",
    status: "In Review",
    owner: "Utilities – BLM",
    createdAt: "2026-09-10T18:43:32Z",
    updatedAt: "2026-09-10T19:02:10Z",
  },
  {
    id: "ALT-2039",
    ticketKey: "SPOT-ONT-0909-063:IP-602:acoustic",
    missionId: "SPOT-ONT-0909-063",
    inspectionId: "IP-602",
    title: "Bearing defect signature",
    description: "Acoustic capture indicates an early bearing defect on compressor 3.",
    severity: "High",
    status: "Open",
    owner: "Reliability – ONT",
    createdAt: "2026-09-09T22:28:11Z",
    updatedAt: "2026-09-09T22:38:01Z",
  },
  {
    id: "ALT-2028",
    ticketKey: "SPOT-JAX-0908-017:IP-181:steam",
    missionId: "SPOT-JAX-0908-017",
    inspectionId: "IP-181",
    title: "Steam trap failed open",
    description: "Continuous flow pattern is consistent with a failed-open steam trap.",
    severity: "Medium",
    status: "Resolved",
    owner: "Utilities – JAX",
    createdAt: "2026-09-08T14:20:18Z",
    updatedAt: "2026-09-09T12:14:00Z",
  },
  {
    id: "ALT-2017",
    ticketKey: "SPOT-BLM-0906-039:IP-351:thermal",
    missionId: "SPOT-BLM-0906-039",
    inspectionId: "IP-351",
    title: "Oven chain drive temperature high",
    description: "Surface temperature exceeded the thermal inspection limit by 12.4 °C.",
    severity: "Critical",
    status: "In Review",
    owner: "Maintenance – BLM",
    createdAt: "2026-09-06T17:49:52Z",
    updatedAt: "2026-09-07T13:20:00Z",
  },
];

const integrationLogs = [
  { id: "LOG-8814", time: "2026-09-10T18:48:25Z", eventId: "evt-spot-blm-0910-042", correlationId: "corr-0042-arch", stage: "ARCH delivery", outcome: "Delivered", detail: "Mission and 2 ticket updates accepted" },
  { id: "LOG-8813", time: "2026-09-10T18:48:24Z", eventId: "evt-spot-blm-0910-042", correlationId: "corr-0042-arch", stage: "Litmus mapping", outcome: "Mapped", detail: "5 inspections, 3 attachments" },
  { id: "LOG-8812", time: "2026-09-10T18:48:23Z", eventId: "evt-spot-blm-0910-042", correlationId: "corr-0042-arch", stage: "Orbit webhook", outcome: "Validated", detail: "action.completed_with_alert" },
  { id: "LOG-8806", time: "2026-09-10T15:18:12Z", eventId: "evt-spot-blm-0910-041", correlationId: "corr-0041-arch", stage: "ARCH delivery", outcome: "Delivered", detail: "Mission accepted" },
  { id: "LOG-8792", time: "2026-09-09T22:37:49Z", eventId: "evt-spot-ont-0909-063", correlationId: "corr-0063-arch", stage: "ARCH delivery", outcome: "Delivered", detail: "Mission and ticket update accepted" },
];

module.exports = { plants, missions, alerts, integrationLogs };
